# Use a lightweight Node.js base image
FROM node:lts-alpine

# Create the working directory for the app
WORKDIR /app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the React app files
COPY . ./

# Build the React app for production
RUN npm run build

# Expose the port the app will listen on
EXPOSE 3000

# Start the app
CMD ["npm", "start"]
