# Use the official Node.js image with a specified version
FROM node:18.17.1

# Create and set the working directory inside the container
WORKDIR /usr/src/app

# Copy package.json and package-lock.json to the working directory
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the entire source code to the working directory
COPY ./src ./src
COPY .env .env
COPY tsconfig.json ./
COPY .eslintrc.js ./
COPY .gitignore ./

# Expose the port your app runs on
EXPOSE 5000

# Set environment variables
ENV PORT=5000
ENV KEY="Bearer eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiI5YTYyMTQ1MDNiOTk1NjRhZDViYjUzODY2Mzg3ZWEzZiIsInN1YiI6IjY1OTI0YTVlNTcxNzZmNmI3NTdmYWRhYiIsInNjb3BlcyI6WyJhcGlfcmVhZCJdLCJ2ZXJzaW9uIjoxfQ.9v5fGBcZaApGKRaY4_2Nw51j8Hlhkg_CnM32NOYhSlY"

# Command to run your application
CMD ["npm", "start"]
